-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 22:38:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vitalsense_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vitalsense_db` ;

-- -----------------------------------------------------
-- Schema vitalsense_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vitalsense_db` DEFAULT CHARACTER SET utf8 ;
USE `vitalsense_db` ;

-- -----------------------------------------------------
-- Table `vitalsense_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`users` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `USER_LAST_NAME` VARCHAR(45) NOT NULL,
  `USER_EMAIL` VARCHAR(45) NOT NULL,
  `USER_PASSWORD` VARCHAR(45) NOT NULL,
  `USER_PROFILE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`patients` (
  `PAT_ID` INT NOT NULL AUTO_INCREMENT,
  `PAT_BIRTHDATE` DATE NOT NULL,
  `PAT_GENRE` VARCHAR(45) NOT NULL,
  `PAT_ADDRESS` VARCHAR(45) NOT NULL,
  `PAT_PHONE_NUMBER` INT NULL,
  `PAT_OTHER_INFO` VARCHAR(100) NULL,
  `PAT_IDCC` INT NOT NULL,
  `users_USER_ID` INT NOT NULL,
  PRIMARY KEY (`PAT_ID`),
  INDEX `fk_patients_users_idx` (`users_USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_patients_users`
    FOREIGN KEY (`users_USER_ID`)
    REFERENCES `vitalsense_db`.`users` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`doctor` (
  `DOC_ID` INT NOT NULL AUTO_INCREMENT,
  `DOC_NAME` VARCHAR(45) NOT NULL,
  `DOC_LAST_NAME` VARCHAR(45) NOT NULL,
  `DOC_EMAIL` VARCHAR(45) NOT NULL,
  `DOC_SPECIALITY` VARCHAR(45) NULL,
  `DOC_LICENSE_NUMBER` INT NOT NULL,
  `DOC_PHONE_NUMBER` INT NOT NULL,
  `users_USER_ID` INT NOT NULL,
  `patients_PAT_ID` INT NOT NULL,
  PRIMARY KEY (`DOC_ID`),
  INDEX `fk_doctor_users1_idx` (`users_USER_ID` ASC) VISIBLE,
  INDEX `fk_doctor_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_users1`
    FOREIGN KEY (`users_USER_ID`)
    REFERENCES `vitalsense_db`.`users` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`carer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`carer` (
  `CAR_ID` INT NOT NULL AUTO_INCREMENT,
  `CAR_NAME` VARCHAR(45) NOT NULL,
  `CAR_LAST_NAME` VARCHAR(45) NOT NULL,
  `CAR_RELATIONSHIP` VARCHAR(45) NOT NULL,
  `CAR_PHONE_NUMBER` INT NOT NULL,
  `CAR_EMAIL` VARCHAR(45) NOT NULL,
  `CAR_ADDRESS` VARCHAR(45) NOT NULL,
  `CAR_IDCC` INT NOT NULL,
  `users_USER_ID` INT NOT NULL,
  `patients_PAT_ID` INT NOT NULL,
  PRIMARY KEY (`CAR_ID`),
  INDEX `fk_carer_users1_idx` (`users_USER_ID` ASC) VISIBLE,
  INDEX `fk_carer_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_carer_users1`
    FOREIGN KEY (`users_USER_ID`)
    REFERENCES `vitalsense_db`.`users` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carer_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`observations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`observations` (
  `OBS_ID` INT NOT NULL AUTO_INCREMENT,
  `OBS_DATE` DATETIME NOT NULL,
  `OBS_INFORMATION` VARCHAR(1000) NOT NULL,
  `patients_PAT_ID` INT NOT NULL,
  `carer_CAR_ID` INT NOT NULL,
  PRIMARY KEY (`OBS_ID`),
  INDEX `fk_observations_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  INDEX `fk_observations_carer1_idx` (`carer_CAR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_observations_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observations_carer1`
    FOREIGN KEY (`carer_CAR_ID`)
    REFERENCES `vitalsense_db`.`carer` (`CAR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`comorbidities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`comorbidities` (
  `COMOR_ID` INT NOT NULL AUTO_INCREMENT,
  `COMOR_NAME` VARCHAR(45) NOT NULL,
  `COMOR_DESCRIPTION` VARCHAR(1000) NOT NULL,
  `COMOR_DIAGNOSIS_DATE` DATETIME NOT NULL,
  `COMOR_TREATMENT` VARCHAR(1000) NULL,
  `patients_PAT_ID` INT NOT NULL,
  PRIMARY KEY (`COMOR_ID`),
  INDEX `fk_comorbidities_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_comorbidities_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`nurses` (
  `NUR_ID` INT NOT NULL AUTO_INCREMENT,
  `NUR_NAME` VARCHAR(45) NOT NULL,
  `NUR_LAST_NAME` VARCHAR(45) NOT NULL,
  `NUR_EMAIL` VARCHAR(45) NOT NULL,
  `NUR_SPECIALITY` VARCHAR(45) NULL,
  `NUR_LICENSE_NUMBER` INT NOT NULL,
  `NUR_PHONE_NUMBER` VARCHAR(45) NULL,
  `users_USER_ID` INT NOT NULL,
  `patients_PAT_ID` INT NOT NULL,
  PRIMARY KEY (`NUR_ID`),
  INDEX `fk_nurses_users1_idx` (`users_USER_ID` ASC) VISIBLE,
  INDEX `fk_nurses_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_nurses_users1`
    FOREIGN KEY (`users_USER_ID`)
    REFERENCES `vitalsense_db`.`users` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nurses_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`exams` (
  `EXA_ID` INT NOT NULL AUTO_INCREMENT,
  `EXA_TYPE` VARCHAR(45) NOT NULL,
  `EXA_DATE` DATE NOT NULL,
  `EXA_RESULT` VARCHAR(1000) NULL,
  `EXA_RESPONSIBLE` VARCHAR(45) NOT NULL,
  `EXA_COMMENTS` VARCHAR(1000) NULL,
  `patients_PAT_ID` INT NOT NULL,
  `EXA_NAME_LAB` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EXA_ID`),
  INDEX `fk_exams_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_exams_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`nursing_visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`nursing_visits` (
  `VNUR_ID` INT NOT NULL AUTO_INCREMENT,
  `VNUR_DATE` DATE NOT NULL,
  `VNUR_COMMENTS` VARCHAR(1000) NULL,
  `VNUR_PROCEDURES` VARCHAR(1000) NOT NULL,
  `VNUR_ADMINISTERED_MEDICATIONS` VARCHAR(500) NOT NULL,
  `patients_PAT_ID` INT NOT NULL,
  `nurses_NUR_ID` INT NOT NULL,
  PRIMARY KEY (`VNUR_ID`),
  INDEX `fk_nursing_visits_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  INDEX `fk_nursing_visits_nurses1_idx` (`nurses_NUR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_nursing_visits_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nursing_visits_nurses1`
    FOREIGN KEY (`nurses_NUR_ID`)
    REFERENCES `vitalsense_db`.`nurses` (`NUR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`medicines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`medicines` (
  `MED_ID` INT NOT NULL AUTO_INCREMENT,
  `MED_NAME` VARCHAR(45) NOT NULL,
  `MED_DESCRIPTION` VARCHAR(500) NULL,
  `MED_START_DATE` DATE NOT NULL,
  `MED_END_DATE` DATE NOT NULL,
  `MED_INSTRUCTIONS` VARCHAR(1000) NOT NULL,
  `MED_COMMENTS` VARCHAR(1000) NULL,
  `patients_PAT_ID` INT NOT NULL,
  PRIMARY KEY (`MED_ID`),
  INDEX `fk_medicines_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_medicines_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`doctor_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`doctor_visit` (
  `VDOC_ID` INT NOT NULL AUTO_INCREMENT,
  `VDOC_DATE` DATE NOT NULL,
  `VDOC_COMMENTS` VARCHAR(1000) NULL,
  `VDOC_ADVICES` VARCHAR(1000) NULL,
  `patients_PAT_ID` INT NOT NULL,
  `doctor_DOC_ID` INT NOT NULL,
  PRIMARY KEY (`VDOC_ID`),
  INDEX `fk_doctor_visit_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  INDEX `fk_doctor_visit_doctor1_idx` (`doctor_DOC_ID` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_visit_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_visit_doctor1`
    FOREIGN KEY (`doctor_DOC_ID`)
    REFERENCES `vitalsense_db`.`doctor` (`DOC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`diagnosis` (
  `DIAG_ID` INT NOT NULL AUTO_INCREMENT,
  `DIAG_DATE` DATE NOT NULL,
  `DIAG_DESCRIPTION` VARCHAR(1000) NOT NULL,
  `DIAG_TREATMENT` VARCHAR(1000) NOT NULL,
  `patients_PAT_ID` INT NOT NULL,
  `doctor_DOC_ID` INT NOT NULL,
  `exams_EXA_ID` INT NOT NULL,
  PRIMARY KEY (`DIAG_ID`),
  INDEX `fk_diagnosis_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  INDEX `fk_diagnosis_doctor1_idx` (`doctor_DOC_ID` ASC) VISIBLE,
  INDEX `fk_diagnosis_exams1_idx` (`exams_EXA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_diagnosis_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnosis_doctor1`
    FOREIGN KEY (`doctor_DOC_ID`)
    REFERENCES `vitalsense_db`.`doctor` (`DOC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnosis_exams1`
    FOREIGN KEY (`exams_EXA_ID`)
    REFERENCES `vitalsense_db`.`exams` (`EXA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`heart_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`heart_rate` (
  `HRATE_ID` INT NOT NULL AUTO_INCREMENT,
  `HRATE_DATE` DATETIME NOT NULL,
  `HRATE_VALUE` INT NOT NULL,
  `patients_PAT_ID` INT NOT NULL,
  PRIMARY KEY (`HRATE_ID`),
  INDEX `fk_heart_rate_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_heart_rate_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalsense_db`.`oximetry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalsense_db`.`oximetry` (
  `OXI_ID` INT NOT NULL AUTO_INCREMENT,
  `OXI_DATE` DATETIME NOT NULL,
  `OXI_VALUE` INT NULL,
  `patients_PAT_ID` INT NOT NULL,
  PRIMARY KEY (`OXI_ID`),
  INDEX `fk_oximetry_patients1_idx` (`patients_PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_oximetry_patients1`
    FOREIGN KEY (`patients_PAT_ID`)
    REFERENCES `vitalsense_db`.`patients` (`PAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
