version: "3.3"
services:
    mysql:
        image: docker.io/mariadb:10.1
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: vitalsense_db
            MYSQL_USER: vitalsense_db
            MYSQL_PASSWORD: password
        networks:
            default:
                ipv4_address: 172.18.0.3

networks:
  default:
    external:
      name: vagrant_backend-VitalSense